= Knogler Fußballliga
:toc:
:sectnums:
:icons: font

== User Stories

Als Person möchte ich einen Vertrag mit einem Verein eingehen.

Als Team möchte ich bei einem Match teilnehmen.

Als Person möchte ich bei einem Match als Stürmer mitspielen.


== Use Case Diagram
[plantuml, target=./images/anwend-diag, format=png]
....
@startuml
left to right direction

usecase "spielt match" as UC1

usecase "tragt matchergebnisse ein" as UC2

usecase "asda" as UC3

Person --> UC1
Team --> UC2
Person --> UC3
@enduml
....


== CLD

["plantuml", "cld"]
----
include::cld.puml[]
----

== Fragen
=== Was bedeutet Stashing? In welchen Situationen wird dieses angewendet?
[TIP]
Beim Stashing wird der aktuelle lokale Zwischenstand versteckt bzw zwischengespeichert. Somit kann in einen anderen Branch gewechselt werden. Z.B wird auf einem Feature Branch ein Feature entwickelt, welches aber noch nicht bereit zum committen ist. Es muss aber auf einem anderen Branch ein Bug schnellstmöglich behoben werden. Mit stashing kann der aktuelle lokal Stand des Feature Branches gesichert werden ohne committet zu werden und es kann ohne Probleme am anderen Branch der Bug behoben werden.

=== Was bedeutet Cherry Picking? In welchen Situationen wird dieses angewendet?
[TIP]
//Cherry Picking beschreibt das gezielte heraussuchen und clonen eines bestimmten commits (meist in einem anderen Branch)
//Dies erfolgt wennd der Stand eines bestimmten Commits zb in einem anderen Branch gebraucht wird.

Beim Cherry Picking kann ein bestimmter Commit aus einem anderen Branch auf den derzeitigen Head angewendet werden. Z.B wenn am frontend gearbeitet wird, aber ein Patch commmit im backend gemacht wurde, kann der Entwickler am Frontend den Patch commit in seinen Branch übernehmen und so mit dem Bug freien Backend weiterarbeiten.

=== Welche Möglichkeiten gibt es zur Container-Orchestrierung?
[TIP]
Z.b Kubernetes, Docker Compose

==== In welchen Situationen werden diese Möglichkeiten verwendet?
[TIP]
Bei der Orchestrierung kann z.B festgelegt werden, dass der Container der die DB beinhaltet als erstes Startet und erst
dann der Server, der die DB benötigt. Z.b kann aber auch der Container, der das Frontend beinhaltet, erst gestartet
werden wenn der Container, der das Backend beinhaltet, erfolgreich gestartet worden ist.

=== Erläutern Sie den Unterschied zwischen Product Backlog und Sprint Backlog
[TIP]
Im Product Backlog befinden sich alle Funktionalitäten, die im Laufe der Projektentwicklung implementiert werden müssen.
Der Sprint Backlog beinhaltet alle Punkte, die im aktuellen Sprit implementiert werden müssen.
(also eine Untermenge des Product Backlogs)

=== Was versteht man unter einer Lookup-Table?
[TIP]
Ein Lookup table ist eine meist alleinstehende Tabelle, die Daten enthält auf die Öfters zugegriffen werden müssen (meist daten die nicht kalkuliert werden könenn z.B Postleitzahlen, Telefonnummern, etc).
